name: Artifacts React App
permissions: 
  contents: write
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v6
      - name: Install Node v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm install
      - name: test
        run : npm run test > test.txt
      - name: Uplaod Test
        uses: actions/upload-artifact@v4
        with:
          name: testing
          path: test.txt
      
  download-test:
    name: Download Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: DownlaodTest
        uses: actions/download-artifact@v5
        with:
          name: testing
      - name: Print result
        shell: bash
        run: |
          ls -R
          value='cat test.txt'
          echo $value


      